name: dicom-manager

services:
  dicom-manager:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: dicom-manager
    restart: unless-stopped
    command: ["./service"]
    depends_on:
      - postgres
    env_file:
      - ../.env
    environment:
      - APP_NAME=dicom-manager
      - DB_USER=${DICOM_MANAGER_DB_USER}
      - DB_PASSWORD=${DICOM_MANAGER_DB_PASSWORD}
      - DB_NAME=${DICOM_MANAGER_DB_NAME}
      - DB_HOST=${DICOM_MANAGER_DB_HOST}
      - DB_PORT=${DICOM_MANAGER_DB_PORT}
    ports:
      - "11000"
    networks:
      - dicom-network

  dicom-manager-poller:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: dicom-manager-poller
    restart: unless-stopped
    command: ["./poller"]
    depends_on:
      - postgres
    env_file:
      - ../.env
    environment:
      - APP_NAME=dicom-manager-poller
      - DB_USER=${DICOM_MANAGER_DB_USER}
      - DB_PASSWORD=${DICOM_MANAGER_DB_PASSWORD}
      - DB_NAME=${DICOM_MANAGER_DB_NAME}
      - DB_HOST=${DICOM_MANAGER_DB_HOST}
      - DB_PORT=${DICOM_MANAGER_DB_PORT}
    networks:
      - dicom-network

  postgres:
    image: postgres:17-alpine
    container_name: dicom-manager-postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DICOM_MANAGER_DB_USER} -d ${DICOM_MANAGER_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - ../.env
    environment:
      - POSTGRES_USER=${DICOM_MANAGER_DB_USER}
      - POSTGRES_PASSWORD=${DICOM_MANAGER_DB_PASSWORD}
      - POSTGRES_DB=${DICOM_MANAGER_DB_NAME}
    ports:
      - "5432"
    networks:
      - dicom-network

networks:
  dicom-network:
    external: true
