syntax = "proto3";

package api.dicom.worker;
option go_package = "internal/generated/dicom-worker;dicom_worker";

import "google/protobuf/timestamp.proto";

service DicomWorkerService {
  // ProcessDicom обработка одного DICOM объекта.
  rpc ProcessDicom (ProcessDicomIn) returns (ProcessDicomOut) {}
  // ProcessDicomBatch обработка батча DICOM объектов.
  rpc ProcessDicomBatch (stream ProcessDicomBatchIn) returns (stream ProcessDicomBatchOut) {}
  // GetJobInfo получение информации о джобе обработки.
  rpc GetJobInfo (GetJobInfoIn) returns (GetJobInfoOut) {}
  // GetJobInfoByIDs получение информации о нескольких джобах обработки.
  rpc GetJobInfoByIDs (GetJobInfoByIDsIn) returns (GetJobInfoByIDsOut) {}
}

enum JobStatus {
  JOB_STATUS_UNSPECIFIED = 0;
  JOB_STATUS_PENDING     = 1;
  JOB_STATUS_RUNNING     = 2;
  JOB_STATUS_COMPLETED   = 3;
  JOB_STATUS_FAILED      = 4;
}

message DicomData {
  string id = 1; // UID из Orthanc (instanceID).
}

message ProcessDicomIn {
  DicomData dicom = 1;
}

message ProcessDicomOut {
  string job_id = 1;
}

message ProcessDicomBatchIn {
  repeated DicomData dicoms = 1;
}

message ProcessDicomBatchOut {
  repeated string job_ids = 1;
}

message JobInfo {
  string                    job_id     = 1;
  JobStatus                 status     = 2;
  google.protobuf.Timestamp created_at = 3;
  google.protobuf.Timestamp updated_at = 4;
}

message GetJobInfoIn {
  string job_id = 1;
}

message GetJobInfoOut {
  JobInfo job = 1;
}

message GetJobInfoByIDsIn {
  repeated string job_ids = 1;
}

message GetJobInfoByIDsOut {
  repeated JobInfo job = 1;
}
