name: dicom-nats-cluster

services:
  nats-1:
    image: docker.io/nats:2.12
    container_name: nats-1
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "4222:4222"
      - "8222:8222"

    volumes:
      - ./nats.conf:/etc/nats/nats-server.conf:ro
      - nats_1_data:/data

    command:
      - "--config"
      - "/etc/nats/nats-server.conf"
      - "--name"
      - "nats-1"

  nats-2:
    image: docker.io/nats:2.12
    container_name: nats-2
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "4223:4222"
      - "8223:8222"

    volumes:
      - ./nats.conf:/etc/nats/nats-server.conf:ro
      - nats_2_data:/data

    command:
      - "--config"
      - "/etc/nats/nats-server.conf"
      - "--name"
      - "nats-2"

  nats-3:
    image: docker.io/nats:2.12
    container_name: nats-3
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "4224:4222"
      - "8224:8222"

    volumes:
      - ./nats.conf:/etc/nats/nats-server.conf:ro
      - nats_3_data:/data

    command:
      - "--config"
      - "/etc/nats/nats-server.conf"
      - "--name"
      - "nats-3"

volumes:
  nats_1_data:
  nats_2_data:
  nats_3_data: