# ============================================================
# General
# ============================================================

port: 4222
http: 0.0.0.0:8222


# ============================================================
# Cluster
# ============================================================

cluster {
  name: c1
  listen: 0.0.0.0:6222

  authorization {
    user: nats-route
    password: $NATS_ROUTE_PASSWORD
  }

  routes: [
    nats://nats-route:<need-real-password-here>@nats-1:6222
    nats://nats-route:<need-real-password-here>@nats-2:6222
    nats://nats-route:<need-real-password-here>@nats-3:6222
  ]
}


# ============================================================
# Accounts
# ============================================================

accounts {
  $SYS {
    users: [
      {
        user: sys
        password: $NATS_SYS_PASSWORD
      }
    ]
  }

  DICOM {
    users: [
      {
        user: dicom-worker
        password: $DICOM_WORKER_PASSWORD
        permissions {
          publish {
            allow: [
              "dicom.analysis.requested"
              "dicom.document.updated"
              "dicom.document.failed"
            ]
          }
          subscribe {
            allow: [
              "dicom.analysis.completed"
              "dicom.analysis.failed"
              "_INBOX.>"
            ]
          }
        }
      }

      {
        user: dicom-manager
        password: $DICOM_MANAGER_PASSWORD
        permissions {
          subscribe {
            allow: [
              "dicom.document.updated"
              "dicom.document.failed"
              "_INBOX.>"
            ]
          }
        }
      }

      {
        user: dicom-analyzer
        password: $DICOM_ANALYZER_PASSWORD
        permissions {
          publish {
            allow: [
              "dicom.analysis.completed"
              "dicom.analysis.failed"
            ]
          }
          subscribe {
            allow: [
              "dicom.analysis.requested"
              "_INBOX.>"
            ]
          }
        }
      }
    ]
  }
}


# ============================================================
# JetStream
# ============================================================

jetstream {
  store_dir: /data
}
