name: dicom-orthanc-server

services:
  orthanc:
    image: orthancteam/orthanc:26.9.0
    container_name: orthanc
    restart: unless-stopped
    depends_on:
      - raw-dicom
    ports:
      - 4242:4242
      - 8042:8042
    secrets:
      - orthanc.json
    environment:
      - AWS_S3_STORAGE_PLUGIN_ENABLED="true"
      - ORTHANC_NAME=${ORTHANC_NAME}
      - ORTHANC_PASSWORD=${ORTHANC_PASSWORD}
      - S3_USER=${S3_USER}
      - S3_PASSWORD=${S3_PASSWORD}

  raw-dicom:
    container_name: raw-dicom
    image: quay.io/minio/minio:latest
    environment:
      - MINIO_ROOT_USER=${S3_USER:-minio}
      - MINIO_ROOT_PASSWORD=${S3_PASSWORD:-minio123}
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - raw_dicom_data:/data

secrets:
  orthanc.json:
    file: orthanc.json

volumes:
  raw_dicom_data: