// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/dicom/upload": {
            "post": {
                "description": "Загрузить DICOM файл на сервер.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dicom"
                ],
                "summary": "Загрузить DICOM файл",
                "parameters": [
                    {
                        "type": "file",
                        "description": "DICOM файл для загрузки.",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Файл успешно загружен.",
                        "schema": {
                            "$ref": "#/definitions/dicom_upload.DicomUploadOut"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/dicom/upload/batch": {
            "post": {
                "description": "Загрузить несколько DICOM файлов на сервер в одном запросе.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dicom"
                ],
                "summary": "Загрузить DICOM файлы батчами",
                "parameters": [
                    {
                        "type": "file",
                        "description": ".zip архив с DICOM файлами для загрузки.",
                        "name": "files",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Файлы успешно загружены.",
                        "schema": {
                            "$ref": "#/definitions/dicom_upload_batch.DicomUploadBatchOut"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/dicom/{dicom_id}/image": {
            "get": {
                "description": "Получить изображение DICOM по его идентификатору. Можно указать флаг raw, чтобы получить байты изображения вместо base64.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dicom"
                ],
                "summary": "Получить изображение DICOM",
                "parameters": [
                    {
                        "type": "string",
                        "description": "DICOM ID",
                        "name": "dicom_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Флаг, указывающий, что нужно вернуть байты изображения вместо base64.",
                        "name": "raw",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "DICOM изображение успешно получено.",
                        "schema": {
                            "$ref": "#/definitions/dicom_get_image.DicomGetImageOut"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Доступ запрещен.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "DICOM изображение не найдено.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/job/info": {
            "get": {
                "description": "Получить информацию о задачах на обработку DICOM-файлов по их ID с пагинацией",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "job"
                ],
                "summary": "Получить информацию о задачах на обработку DICOM-файлов по их ID с пагинацией",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Offset для пагинации (по умолчанию 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit для пагинации (по умолчанию 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о задачах успешно получена.",
                        "schema": {
                            "$ref": "#/definitions/job_info_get_by_ids.JobInfoGetPaginatedOut"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Доступ запрещен.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/job/info/{job_id}": {
            "get": {
                "description": "Получить информацию о задаче на обработку DICOM-файла по ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "job"
                ],
                "summary": "Получить информацию о задаче на обработку DICOM-файла по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID задачи на обработку DICOM-файла",
                        "name": "job_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о задаче успешно получена.",
                        "schema": {
                            "$ref": "#/definitions/job_info_get_by_id.JobInfoGetByIDOut"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Доступ запрещен.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Задача не найдена.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/job/result/decision": {
            "post": {
                "description": "Принять решение по результатам обработки DICOM-файлов по их ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "job"
                ],
                "summary": "Принять решение по результатам обработки DICOM-файлов.",
                "parameters": [
                    {
                        "description": "Данные для принятия решения по результатам обработки DICOM-файлов",
                        "name": "JobResultDecision",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/job_result_decision.JobResultDecisionIn"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Решение по результатам обработки успешно принято.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Доступ запрещен.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/report": {
            "get": {
                "description": "Получить отчеты по результатам обработки DICOM-файлов с пагинацией.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "report"
                ],
                "summary": "Получить отчеты по результатам обработки DICOM-файлов.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Offset для пагинации (по умолчанию 0)",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limit для пагинации (по умолчанию 10)",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Отчеты по результатам обработки DICOM-файлов успешно получены.",
                        "schema": {
                            "$ref": "#/definitions/report_get_by_id.ReportGetPaginatedOut"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Доступ запрещен.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/report/generate": {
            "post": {
                "description": "Сгенерировать отчет по результатам обработки DICOM-файлов в формате .csv.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "report"
                ],
                "summary": "Сгенерировать отчет по результатам обработки DICOM-файлов.",
                "parameters": [
                    {
                        "description": "ID для генерации отчета по результатам обработки DICOM-файлов",
                        "name": "ReportGenerateIn",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/report_generate.ReportGenerateIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Отчет по результатам обработки DICOM-файлов успешно сгенерирован.",
                        "schema": {
                            "$ref": "#/definitions/report_generate.ReportGenerateOut"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Доступ запрещен.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/report/{report_id}": {
            "get": {
                "description": "Получить отчет по результатам обработки DICOM-файлов по ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "report"
                ],
                "summary": "Получить отчет по результатам обработки DICOM-файлов.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID отчета по результатам обработки DICOM-файлов",
                        "name": "report_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Отчет по результатам обработки DICOM-файлов успешно получены.",
                        "schema": {
                            "$ref": "#/definitions/report_get_by_id.ReportGetByIDOut"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Доступ запрещен.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Отчет не найден.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "Аутентификация пользователя по его логину и паролю.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Аутентификация пользователя.",
                "parameters": [
                    {
                        "description": "Данные для аутентификации пользователя",
                        "name": "UserLoginIn",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user_login.UserLoginIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Пользователь успешно аутентифицирован.",
                        "schema": {
                            "$ref": "#/definitions/user_login.UserLoginOut"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Неверный логин или пароль.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/{user_id}": {
            "get": {
                "description": "Получить информацию о пользователе по его ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Получить информацию о пользователе.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID пользователя",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о пользователе успешно получена.",
                        "schema": {
                            "$ref": "#/definitions/user_info_get_by_id.UserGetInfoOut"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Доступ запрещен.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Пользователь не найден.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dicom_get_image.DicomGetImageOut": {
            "description": "Если Raw=false, то возвращается base64 изображения. Если Raw=true, то возвращаются байты изображения.",
            "type": "object",
            "properties": {
                "image_data": {
                    "description": "Если Raw=false, то возвращается base64 изображения.",
                    "type": "string"
                },
                "image_data_raw": {
                    "description": "Если Raw=true, то возвращаются байты изображения.",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "dicom_upload.DicomUploadOut": {
            "type": "object",
            "properties": {
                "dicom_id": {
                    "type": "string"
                },
                "job_id": {
                    "description": "ID задачи на сервере для обработки DICOM файла.",
                    "type": "string"
                }
            }
        },
        "dicom_upload_batch.DicomData": {
            "type": "object",
            "properties": {
                "dicom_id": {
                    "type": "string"
                },
                "job_id": {
                    "description": "ID задачи на сервере для обработки DICOM файла.",
                    "type": "string"
                }
            }
        },
        "dicom_upload_batch.DicomUploadBatchOut": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Список данных о DICOM файлах и задачах на сервере.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dicom_upload_batch.DicomData"
                    }
                }
            }
        },
        "internal_api_report_get_by_id.Report": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "Дата и время создания отчета по результатам обработки DICOM-файлов.",
                    "type": "string"
                },
                "download_url": {
                    "description": "URL для скачивания отчета по результатам обработки DICOM-файлов.",
                    "type": "string"
                },
                "id": {
                    "description": "ID отчета по результатам обработки DICOM-файлов.",
                    "type": "integer"
                }
            }
        },
        "internal_api_report_get_paginated.Report": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "Дата и время создания отчета по результатам обработки DICOM-файлов.",
                    "type": "string"
                },
                "download_url": {
                    "description": "URL для скачивания отчета по результатам обработки DICOM-файлов.",
                    "type": "string"
                },
                "id": {
                    "description": "ID отчета по результатам обработки DICOM-файлов.",
                    "type": "integer"
                }
            }
        },
        "job_info_get_by_id.JobInfoGetByIDOut": {
            "type": "object",
            "properties": {
                "job": {
                    "description": "Содержит информацию о задаче на обработку DICOM-файлоа.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.JobInfo"
                        }
                    ]
                }
            }
        },
        "job_info_get_by_ids.JobInfoGetPaginatedOut": {
            "type": "object",
            "properties": {
                "jobs": {
                    "description": "Список информации о задачах на обработку DICOM-файлов.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.JobInfo"
                    }
                }
            }
        },
        "job_result_decision.Decision": {
            "type": "string",
            "enum": [
                "approved",
                "rejected",
                "force_approved"
            ],
            "x-enum-comments": {
                "DecisionApprove": "Результат задачи принят специалистом.",
                "DecisionForceApproved": "Результат задачи принят специалистом, несмотря на рекомендацию системы.",
                "DecisionReject": "Результат задачи отклонен специалистом."
            },
            "x-enum-descriptions": [
                "Результат задачи принят специалистом.",
                "Результат задачи отклонен специалистом.",
                "Результат задачи принят специалистом, несмотря на рекомендацию системы."
            ],
            "x-enum-varnames": [
                "DecisionApprove",
                "DecisionReject",
                "DecisionForceApproved"
            ]
        },
        "job_result_decision.JobResultDecisionIn": {
            "type": "object",
            "properties": {
                "comment": {
                    "description": "Комментарий к решению по результатам обработки DICOM-файлов (необязательный).",
                    "type": "string"
                },
                "decision": {
                    "description": "Решение по результатам обработки DICOM-файлов (\"approved\", \"reject\", \"force_approved\").",
                    "allOf": [
                        {
                            "$ref": "#/definitions/job_result_decision.Decision"
                        }
                    ]
                },
                "job_ids": {
                    "description": "Список ID задач на обработку DICOM-файлов, для которых необходимо принять решение по результатам.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "model.Decision": {
            "type": "string",
            "enum": [
                "approved",
                "rejected",
                "force_approved"
            ],
            "x-enum-comments": {
                "DecisionApprove": "Результат задачи принят специалистом.",
                "DecisionForceApproved": "Результат задачи принят специалистом, несмотря на рекомендацию системы.",
                "DecisionReject": "Результат задачи отклонен специалистом."
            },
            "x-enum-descriptions": [
                "Результат задачи принят специалистом.",
                "Результат задачи отклонен специалистом.",
                "Результат задачи принят специалистом, несмотря на рекомендацию системы."
            ],
            "x-enum-varnames": [
                "DecisionApprove",
                "DecisionReject",
                "DecisionForceApproved"
            ]
        },
        "model.JobInfo": {
            "type": "object",
            "properties": {
                "anatomical_region": {
                    "description": "Анатомическая область, к которой относится DICOM-файл.",
                    "type": "string"
                },
                "comment": {
                    "description": "Комментарий специалиста.",
                    "type": "string"
                },
                "confidence": {
                    "description": "Уровень уверенности в результатах обработки от 0 до 1.",
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "dicom_id": {
                    "description": "ID DICOM-файла.",
                    "type": "string"
                },
                "duration_ms": {
                    "description": "Время обработки задачи в миллисекундах.",
                    "type": "integer"
                },
                "id": {
                    "description": "ID задачи на обработку.",
                    "type": "string"
                },
                "metadata": {
                    "description": "Дополнительные метаданные, связанные с задачей.",
                    "type": "object",
                    "additionalProperties": {}
                },
                "specialist_decision": {
                    "description": "Решение специалиста по результату задачи.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.Decision"
                        }
                    ]
                },
                "specialist_id": {
                    "description": "ID специалиста, который принял решение.",
                    "type": "integer"
                },
                "status": {
                    "description": "Статус задачи на обработку.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.JobStatus"
                        }
                    ]
                },
                "updated_at": {
                    "type": "string"
                },
                "violations": {
                    "description": "Список нарушений, обнаруженных в DICOM-файле.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "model.JobStatus": {
            "type": "string",
            "enum": [
                "pending",
                "processing",
                "completed",
                "failed"
            ],
            "x-enum-comments": {
                "JobStatusCompleted": "Задача успешно завершена.",
                "JobStatusFailed": "Задача завершилась с ошибкой.",
                "JobStatusPending": "Задача ожидает обработки.",
                "JobStatusProcessing": "Задача в процессе обработки."
            },
            "x-enum-descriptions": [
                "Задача ожидает обработки.",
                "Задача в процессе обработки.",
                "Задача успешно завершена.",
                "Задача завершилась с ошибкой."
            ],
            "x-enum-varnames": [
                "JobStatusPending",
                "JobStatusProcessing",
                "JobStatusCompleted",
                "JobStatusFailed"
            ]
        },
        "report_generate.ReportGenerateIn": {
            "type": "object",
            "properties": {
                "job_ids": {
                    "description": "Список ID задач на обработку DICOM-файлов, для которых необходимо сгенерировать отчет.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "report_generate.ReportGenerateOut": {
            "type": "object",
            "properties": {
                "report_id": {
                    "description": "ID сгенерированного отчета по результатам обработки DICOM-файлов.",
                    "type": "integer"
                }
            }
        },
        "report_get_by_id.ReportGetByIDOut": {
            "type": "object",
            "properties": {
                "report": {
                    "description": "Содержит отчет по результатам обработки DICOM-файлов.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/internal_api_report_get_by_id.Report"
                        }
                    ]
                }
            }
        },
        "report_get_by_id.ReportGetPaginatedOut": {
            "type": "object",
            "properties": {
                "reports": {
                    "description": "Список отчетов по результатам обработки DICOM-файлов.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_api_report_get_paginated.Report"
                    }
                }
            }
        },
        "user_info_get_by_id.UserGetInfoOut": {
            "type": "object",
            "properties": {
                "full_name": {
                    "description": "Имя пользователя.",
                    "type": "string"
                },
                "id": {
                    "description": "ID пользователя.",
                    "type": "integer"
                },
                "organisation_ids": {
                    "description": "Список ID организаций, к которым принадлежит пользователь.",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "role": {
                    "description": "Роль пользователя (specialist, admin).",
                    "allOf": [
                        {
                            "$ref": "#/definitions/user_info_get_by_id.UserRole"
                        }
                    ]
                }
            }
        },
        "user_info_get_by_id.UserRole": {
            "type": "string",
            "enum": [
                "specialist",
                "admin"
            ],
            "x-enum-comments": {
                "UserRoleAdmin": "Администратор системы.",
                "UserRoleSpecialist": "Специалист, который может принимать решения по обработке DICOM-файлов."
            },
            "x-enum-descriptions": [
                "Специалист, который может принимать решения по обработке DICOM-файлов.",
                "Администратор системы."
            ],
            "x-enum-varnames": [
                "UserRoleSpecialist",
                "UserRoleAdmin"
            ]
        },
        "user_login.UserLoginIn": {
            "type": "object",
            "properties": {
                "password": {
                    "description": "Пароль пользователя для входа в систему.",
                    "type": "string"
                },
                "username": {
                    "description": "Имя пользователя для входа в систему.",
                    "type": "string"
                }
            }
        },
        "user_login.UserLoginOut": {
            "type": "object",
            "properties": {
                "token": {
                    "description": "JWT-токен, который будет использоваться для аутентификации последующих запросов.",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
