info:
  name: Get modality configuration
  type: http
  seq: 5
  tags:
    - Networking

http:
  method: GET
  url: "{{baseUrl}}/modalities/:id/configuration"
  params:
    - name: id
      value: ""
      type: path
      description: Identifier of the modality of interest
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
  forwardAuthorizationHeader: false

examples:
  - name: 200 Response
    request:
      url: "{{baseUrl}}/modalities/:id/configuration"
      method: GET
      params:
        - name: id
          value: ""
          type: path
          description: Identifier of the modality of interest
    response:
      status: 200
      statusText: OK
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "AET": "ORTHANCTEST",
            "AllowEcho": true,
            "AllowEventReport": true,
            "AllowFind": true,
            "AllowFindWorklist": true,
            "AllowGet": true,
            "AllowMove": true,
            "AllowNAction": true,
            "AllowStore": true,
            "AllowTranscoding": true,
            "Host": "127.0.1.1",
            "Manufacturer": "Generic",
            "Port": 5001
          }

docs: Get detailed information about the configuration of some DICOM modality
